

task1: task1.o
	gcc -o task1 task1.o

task1.o: task1.c
	gcc -c task1.c

task2: task2.o
	gcc -o task2 task2.o

task2.o: task2.c
	gcc -c task2.c

task3: task3.o
	gcc -o task3 task3.o

task3.o: task3.c
	gcc -c task3.c

task4: task4.o
	gcc -o task4 task4.o

task4.o: task4.c
	gcc -c task4.c

clean:
	rm -f task1 task2 task3 task4 task1.o task2.o task3.o task4.o
