CC = gcc
CFLAGS = -Wall

TARGETS = output1 output2 output3 output4 output5 output6 output7 output8 \
          number_pyramid factorial loop50 tables value_table average bugged_code smallest

all: $(TARGETS)

output1: output1.c
	$(CC) $(CFLAGS) output1.c -o output1

output2: output2.c
	$(CC) $(CFLAGS) output2.c -o output2

output3: output3.c
	$(CC) $(CFLAGS) output3.c -o output3

output4: output4.c
	$(CC) $(CFLAGS) output4.c -o output4

output5: output5.c
	$(CC) $(CFLAGS) output5.c -o output5

output6: output6.c
	$(CC) $(CFLAGS) output6.c -o output6

output7: output7.c
	$(CC) $(CFLAGS) output7.c -o output7

output8: output8.c
	$(CC) $(CFLAGS) output8.c -o output8

number_pyramid: number_pyramid.c
	$(CC) $(CFLAGS) number_pyramid.c -o number_pyramid

factorial: factorial.c
	$(CC) $(CFLAGS) factorial.c -o factorial

loop50: loop50.c
	$(CC) $(CFLAGS) loop50.c -o loop50

tables: tables.c
	$(CC) $(CFLAGS) tables.c -o tables

value_table: value_table.c
	$(CC) $(CFLAGS) value_table.c -o value_table

average: average.c
	$(CC) $(CFLAGS) average.c -o average

bugged_code: bugged_code.c
	$(CC) $(CFLAGS) bugged_code.c -o bugged_code

smallest: smallest.c
	$(CC) $(CFLAGS) smallest.c -o smallest

clean:
	rm -f $(TARGETS)
